services:
  - type: web
    name: zumrut-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python zumrut_server.py
    envVars:
      - key: PORT
        value: 8765